### ISSUE TITLE
Deleting elements from the tree sometimes breaks diagram

### ISSUE THREAD

**Issue by planger** [eclipse-emfcloud/coffee-editor#180] opened 2019-08-29 11:35 UTC
For instance, delete `Preheat` from the tree, how the diagram will look like this:
![image](https://user-images.githubusercontent.com/588090/63936988-a9bec100-ca61-11e9-94ac-c8b19cc68115.png)

Deletion works however for tasks that first have been added. From how the diagram looks like, it seems to be an ID problem (the decision/merge node suddenly has the bounds of a task node) and other nodes switch positions, etc?

**Comment by eneufeld** [comment] 2020-02-24 13:14
@tortmayr is this a generic glsp issue, or is this a coffee editor specific issue?

**Comment by tortmayr** [comment] 2020-02-24 14:33
This is a coffee editor specific issue . I had a quick look at the corresponding action handler. The delete operation is currently not delegated to the modelserver and is instead executed directly on the local resource.  This is probably the main cause for this issue.

**Comment by sgraband** [comment] 2022-09-22 07:20
I am pretty sure that this is already fixed. At least i cannot reproduce it anymore with #457. So if there a no objections i think we can close this when #457 is merged.

**Closed** 2022-11-04 08:36 UTC
Labels: bug
