### ISSUE TITLE
Save doesn't work after refresh

### ISSUE THREAD

**Issue by aurelio-pennacchio** [eclipse-emfcloud/coffee-editor#436] opened 2022-03-16 09:05 UTC
I downloaded the latest version of the coffee-editor and I started to playing around when I noticed the model-server throwing some exceptions.
Here are the steps to follow to reproduce these errors: 
1. Start of the model-server
2. Start of the glsp-server
3. Start of theia-backend
4. Start of theia-frontend
5. Without opening any semantic or notation resources, refresh the page (this means a new configuration of the workspace)
6. Open and try to save a notation resource without doing any change to the semantic and notation models throws the following exception (after them the save functionality doesn't work anymore):

> Exception in thread "Thread-14" java.lang.NullPointerException
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.closeResource(DefaultModelResourceManager.java:276)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.closeModel(DefaultModelRepository.java:147)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.ReconcilingStrategy$AlwaysReload.reconcileModel(ReconcilingStrategy.java:60)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.AbstractModelWatcher.reconcile(AbstractModelWatcher.java:52)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.handleEvent(FileModelWatcher.java:166)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.run(FileModelWatcher.java:128)
	at java.base/java.lang.Thread.run(Thread.java:829)

While doing the following steps I encountered another exception: 

1. Start of the model-server
2. Start of the glsp-server
3. Start of theia-backend
4. Start of theia-frontend
5. Without opening any semantic or notation resources, refresh the page (this means a new configuration of the workspace)
6. Open a notation resource
7. Try to add an automated task and save the resource
8. Refresh the page 
9. Open the same notation resource and try to save. The model-serve throws the following exception: 

> Exception in thread "Thread-18" java.lang.NullPointerException
	at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:471)
	at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:333)
	at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.broadcastUnbatched(TransactionalEditingDomainImpl.java:818)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.appendNotification(TransactionChangeRecorder.java:320)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.processResourceNotification(TransactionChangeRecorder.java:273)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.notifyChanged(TransactionChangeRecorder.java:239)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.dispatchNotification(NotifyingListImpl.java:261)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.clear(NotifyingListImpl.java:1123)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.doUnload(ResourceImpl.java:1701)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doUnload(XMLResourceImpl.java:720)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.unload(ResourceImpl.java:1721)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.closeResource(DefaultModelResourceManager.java:266)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.closeModel(DefaultModelRepository.java:147)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.ReconcilingStrategy$AlwaysReload.reconcileModel(ReconcilingStrategy.java:60)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.AbstractModelWatcher.reconcile(AbstractModelWatcher.java:52)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.handleEvent(FileModelWatcher.java:166)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.run(FileModelWatcher.java:128)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "Thread-20" java.lang.NullPointerException
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.getDirtyState(DefaultModelResourceManager.java:517)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.getDirtyState(DefaultModelRepository.java:162)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.modelUpdated(DefaultSessionController.java:123)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.ReconcilingStrategy$AlwaysReload.reconcileModel(ReconcilingStrategy.java:73)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.AbstractModelWatcher.reconcile(AbstractModelWatcher.java:52)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.handleEvent(FileModelWatcher.java:166)
	at org.eclipse.emfcloud.modelserver.emf.common.watchers.FileModelWatcher.run(FileModelWatcher.java:128)
	at java.base/java.lang.Thread.run(Thread.java:829)

Thanks in advance for your work and your responses!

**Comment by eneufeld** [comment] 2022-03-16 14:24
Thank you for your report.
Are you on windows?
We are currently updating the modelserver dependencies. I hope that these updates will resolve some of the issues you encounter.

**Comment by aurelio-pennacchio** [comment] 2022-03-17 07:59
I am currently working on Ubuntu 20.04. Thanks for the response!

**Comment by eneufeld** [comment] 2022-03-23 09:39
We updated the dependencies especially the one to the modelserver: https://github.com/eclipse-emfcloud/coffee-editor/pull/439
With the fixes I cannot reproduce your error anymore. We try to merge this soon. If you could try it out, that would be great.

**Comment by aurelio-pennacchio** [comment] 2022-03-24 12:59
With the newest model-server dependencies, model saving after reloading the workspace multiple times works correctly. Thanks a lot!

**Comment by eneufeld** [comment] 2022-03-24 13:57
Thank you for testing and reporting back!

**Comment by eneufeld** [comment] 2022-05-05 09:50
Branch is merged

**Closed by eneufeld** 2022-05-05 09:50 UTC
Labels: bug
