### ISSUE TITLE
Auto Layout action in the workflow diagram has no effect

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/coffee-editor#351] opened 2021-04-01 08:54 UTC
You can click it in the diagram menu, but it has not effect

**Comment by eneufeld** [comment] 2022-01-20 16:30
@tortmayr @ndoschek do you have an idea what this might be caused by?

**Comment by tortmayr** [comment] 2022-01-21 10:31
I had a quick look, however I'm not that familiar with the model-server specific LayoutEngine (ESMLayoutEngine) so maybe  @ndoschek can provide more insights on this.

**Comment by ndoschek** [comment] 2022-01-21 13:32
By merging #419 this should be fixed (during the former update process I fixed that). Also, on current master the auto layout works for me via keyboard shortcut as well as the menu entry.

**Comment by eneufeld** [comment] 2022-01-21 14:23
I double check, maybe something was off for me yesterday.

**Comment by eneufeld** [comment] 2022-01-31 12:37
Works!
Fixed by #419

**Closed by eneufeld** 2022-01-31 12:37 UTC
Labels: bug, glsp, glsp-update
